version: '3'
services:
  blinkt:
    image: phriscage/iot_sys-blinkt:0.3.0
    #cap-add:
      #- SYS_RAWIO
    #devices:
      #- /dev/mem
    volumes:
      - /sys:/sys
    ports:
      - 8080:8080
    #networks:
      #- front
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
#networks:
  #front:
